version: "3.4"

services:
  postgresql:
    image: "sameersbn/postgresql:9.6-2"
    volumes:
      - "./data:/var/lib/postgresql:Z"
    ports:
      - "5432:5432"
    environment:
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=product
      - DB_EXTENSION=pg_trgm
