version: '3.4'

services:
  gotty:
    build:
        context: .
        dockerfile: Dockerfile
    image: jlpz/gotty:RELEASE-centos
    ports:
      - "8080:8080"
    environment:
      - TERM=xterm
