version: '3.4'

services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    #volumes:
      #- ./odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always

  odoo:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "5000:8069"
    tty: true
    command: -- --dev=reload
    #command: odoo scaffold /mnt/extra-addons/test_module
    #volumes:
      #- ./addons:/mnt/extra-addons
      #- ./config:/etc/odoo
      #- ./odoo-web-data:/var/lib/odoo
    restart: always
