version: "3.4"

services:
  jenkins:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
    environment:
      - JENKINS_UC=https://updates.jenkins.io
      - JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTIONS=--argumentsRealm.passwd.admin=admin --argumentsRealm.roles.user=admin --argumentsRealm.roles.admin=admin
      - JENKINS_SLAVE_AGENT_PORT=50000
