version: "3.0"

services:
  traefik:
    image: "traefik:v1.5-alpine"
    command:
      - --docker
      - --docker.swarmmode
      - --docker.watch
      - --web
      - --web.address=:8888
    ports:
      - "80:80"
      - "8888:8888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        condition: any
      update_config:
        delay: 2s
      placement:
         constraints: [node.role == manager]
      labels:
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.example.com"
        - "traefik.docker.network=traefik_external"
        - "traefik.port=8888"
    networks:
      - external

networks:
  external:
    driver: overlay
