version: '3.4'

services:
   mysql:
     image: mysql:5.7
     ports:
       - 3306:3306
     volumes:
       - ./mysql_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: you-will-never-guess
       MYSQL_DATABASE: app
       MYSQL_USER: app
       MYSQL_PASSWORD: app
